// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NewHarrods.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Fashion1 PDP")]
    public partial class Fashion1PDPFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Fashion1.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Fashion1 PDP", "    As a user \r\n\tI want to see all details for Fashion1 products\r\n\tSo that I can " +
                    "make an informed decision", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Buying Controls Section")]
        public virtual void BuyingControlsSection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buying Controls Section", null, ((string[])(null)));
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
  testRunner.Given("I am on a Fashion1 PDP with colour and size", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Brand"});
            table1.AddRow(new string[] {
                        "Title"});
            table1.AddRow(new string[] {
                        "Price"});
            table1.AddRow(new string[] {
                        "ID"});
            table1.AddRow(new string[] {
                        "Colour"});
            table1.AddRow(new string[] {
                        "Size"});
            table1.AddRow(new string[] {
                        "Quantity"});
            table1.AddRow(new string[] {
                        "Delivery & Returns link"});
#line 8
  testRunner.Then("the buying controls section contains the following", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple variants available")]
        [NUnit.Framework.TestCaseAttribute("colours", null)]
        [NUnit.Framework.TestCaseAttribute("sizes", null)]
        public virtual void MultipleVariantsAvailable(string variants, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple variants available", null, exampleTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 19
  testRunner.Given(string.Format("I am on a Fashion1 PDP with multiple {0}", variants), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
  testRunner.Then(string.Format("all {0} are displayed", variants), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Product with no variants")]
        public virtual void ProductWithNoVariants()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Product with no variants", null, ((string[])(null)));
#line 27
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 28
  testRunner.Given("I am on a Fashion1 PDP with no available variants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
  testRunner.Then("no variants are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add in-stock product to bag")]
        public virtual void AddIn_StockProductToBag()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add in-stock product to bag", null, ((string[])(null)));
#line 31
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 32
  testRunner.Given("I am on a Fashion1 PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
  testRunner.And("the product is in stock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
  testRunner.When("I add the product to my bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
  testRunner.Then("a confirmation pane is displayed on screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "go to shopping bag"});
            table2.AddRow(new string[] {
                        "go to checkout"});
#line 36
  testRunner.And("the following options are available", ((string)(null)), table2, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All variants are OOS")]
        public virtual void AllVariantsAreOOS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All variants are OOS", null, ((string[])(null)));
#line 40
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 41
  testRunner.Given("I am on a Fashion1 PDP with colour and size variants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
  testRunner.And("all variants of the product are out of stock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
  testRunner.Then("the out of stock message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
  testRunner.And("there is no option to add the product to the bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("One variant of the product is OOS")]
        [NUnit.Framework.TestCaseAttribute("colour", null)]
        [NUnit.Framework.TestCaseAttribute("size", null)]
        public virtual void OneVariantOfTheProductIsOOS(string variant, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("One variant of the product is OOS", null, exampleTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 47
  testRunner.Given("I am on a Fashion1 PDP with colour and size variants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
  testRunner.And(string.Format("one {0} of the product is out of stock", variant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
  testRunner.Then(string.Format("the out of stock {0} is not displayed as an option", variant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 50
  testRunner.And("other variants can be added to bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Confirmation pane persists")]
        [NUnit.Framework.CategoryAttribute("desktop")]
        public virtual void ConfirmationPanePersists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Confirmation pane persists", null, new string[] {
                        "desktop"});
#line 58
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 59
  testRunner.Given("I am on a Fashion1 PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
  testRunner.And("I have added the product to my bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
  testRunner.And("the cursor has remained over the buying controls", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
  testRunner.Then("the confirmation pane remains displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Social sharing")]
        [NUnit.Framework.TestCaseAttribute("Facebook", null)]
        [NUnit.Framework.TestCaseAttribute("Twitter", null)]
        [NUnit.Framework.TestCaseAttribute("Pinterest", null)]
        public virtual void SocialSharing(string platform, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Social sharing", null, exampleTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 65
  testRunner.Given("I am on a Fashion1 PDP with colour and size variants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 66
  testRunner.When(string.Format("I share via {0}", platform), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
  testRunner.Then(string.Format("the product link is shared on {0}", platform), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Shop More")]
        [NUnit.Framework.TestCaseAttribute("brand", null)]
        [NUnit.Framework.TestCaseAttribute("category", null)]
        public virtual void ShopMore(string option, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Shop More", null, exampleTags);
#line 75
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 76
  testRunner.Given("I am on a Fashion1 PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 77
  testRunner.When(string.Format("I select to shop more {0}", option), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
  testRunner.Then(string.Format("I am taken to the {0} PLP", option), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Overview")]
        public virtual void Overview()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Overview", null, ((string[])(null)));
#line 85
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 86
  testRunner.Given("I am on a Fashion1 PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 87
  testRunner.Then("the product overview is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Breadcrumb")]
        public virtual void Breadcrumb()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Breadcrumb", null, ((string[])(null)));
#line 89
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 90
  testRunner.Given("I am on a Fashion1 PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 91
  testRunner.Then("the breadcrumb is present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 92
  testRunner.And("each part of the breadcrumb links to the correct page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Product associations")]
        public virtual void ProductAssociations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Product associations", null, ((string[])(null)));
#line 94
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 95
  testRunner.Given("I am on a Fashion1 PDP which has product associations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "main image"});
            table3.AddRow(new string[] {
                        "brand"});
            table3.AddRow(new string[] {
                        "product name"});
            table3.AddRow(new string[] {
                        "price"});
#line 96
  testRunner.Then("each assocation displays the following", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Product association quickshop panel")]
        [NUnit.Framework.CategoryAttribute("desktop")]
        public virtual void ProductAssociationQuickshopPanel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Product association quickshop panel", null, new string[] {
                        "desktop"});
#line 103
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 104
  testRunner.Given("I am on a Fashion1 PDP which has product associations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 105
  testRunner.When("I open the quickshop panel for an assocation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "image carousel"});
            table4.AddRow(new string[] {
                        "brand"});
            table4.AddRow(new string[] {
                        "product name"});
            table4.AddRow(new string[] {
                        "price"});
            table4.AddRow(new string[] {
                        "ID"});
            table4.AddRow(new string[] {
                        "size"});
            table4.AddRow(new string[] {
                        "colour"});
            table4.AddRow(new string[] {
                        "full details link"});
#line 106
  testRunner.Then("the following is displayed", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Product association add to bag (in stock)")]
        [NUnit.Framework.CategoryAttribute("desktop")]
        public virtual void ProductAssociationAddToBagInStock()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Product association add to bag (in stock)", null, new string[] {
                        "desktop"});
#line 117
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 118
  testRunner.Given("I am on a Fashion1 PDP which has product associations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 119
  testRunner.When("I add an associated product to bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 120
  testRunner.Then("the product is added to my bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Product association add to bag (one variant OOS)")]
        [NUnit.Framework.CategoryAttribute("desktop")]
        [NUnit.Framework.TestCaseAttribute("colour", null)]
        [NUnit.Framework.TestCaseAttribute("size", null)]
        public virtual void ProductAssociationAddToBagOneVariantOOS(string variant, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "desktop"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Product association add to bag (one variant OOS)", null, @__tags);
#line 123
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 124
  testRunner.Given("I am on a Fashion1 PDP which has product associations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 125
  testRunner.And(string.Format("one {0} of the associated product is out of stock", variant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
  testRunner.Then(string.Format("the out of stock {0} is not displayed as an option", variant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 127
  testRunner.And("other variants can be added to bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Product association add to bag (all variants OOS)")]
        [NUnit.Framework.CategoryAttribute("desktop")]
        public virtual void ProductAssociationAddToBagAllVariantsOOS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Product association add to bag (all variants OOS)", null, new string[] {
                        "desktop"});
#line 136
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 137
  testRunner.Given("I am on a Fashion1 PDP which has product associations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 138
  testRunner.And("all variants of the associated product are out of stock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
  testRunner.Then("the out of stock message is not displayed on the quickshop panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 140
  testRunner.And("there is no option to add the assocaited product to the bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Size guide")]
        public virtual void SizeGuide()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Size guide", null, ((string[])(null)));
#line 142
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 143
  testRunner.Given("I am on a Fashion1 PDP with a size guide", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 144
  testRunner.When("I open the size guide module", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 145
  testRunner.Then("the relevant size guide information is displayed for the product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Size guide with fit notes")]
        public virtual void SizeGuideWithFitNotes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Size guide with fit notes", null, ((string[])(null)));
#line 147
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 148
  testRunner.Given("I am on a Fashion1 PDP which has fit notes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 149
  testRunner.When("I open the size guide module", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
  testRunner.Then("the relevant fit notes information is displayed for the product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 151
  testRunner.And("the model image is displayed as the background", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delivery & Returns")]
        public virtual void DeliveryReturns()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delivery & Returns", null, ((string[])(null)));
#line 153
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 154
  testRunner.Given("I am on a Fashion1 PDP with delivery & returns", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 155
  testRunner.When("I open the delivery & returns module", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
  testRunner.Then("delivery and returns information is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Image carousel")]
        [NUnit.Framework.TestCaseAttribute("right", "next", null)]
        [NUnit.Framework.TestCaseAttribute("left", "previous", null)]
        public virtual void ImageCarousel(string direction, string position, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Image carousel", null, exampleTags);
#line 158
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 159
  testRunner.Given("I am on a Fashion1 PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 160
  testRunner.Then("image thumbnails are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 161
  testRunner.When(string.Format("I navigate {0} through the image carousel", direction), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 162
  testRunner.Then(string.Format("the {0} image is displayed", position), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Image pagination")]
        public virtual void ImagePagination()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Image pagination", null, ((string[])(null)));
#line 169
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 170
  testRunner.Given("I am on a Fashion1 PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 171
  testRunner.Then("image thumbnails are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 172
  testRunner.When("I navigate through the image pagination", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 173
  testRunner.Then("the correct image is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Zoom image")]
        public virtual void ZoomImage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Zoom image", null, ((string[])(null)));
#line 175
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 176
  testRunner.Given("I am on a Fashion1 PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 177
  testRunner.When("I select to zoom the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 178
  testRunner.Then("the image is displayed as zoomed in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
