// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NewHarrods.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PDP")]
    public partial class PDPFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PDP.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PDP", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("user is on the homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add to bag from PDP")]
        public virtual void AddToBagFromPDP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add to bag from PDP", null, ((string[])(null)));
#line 9
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 10
 testRunner.Given("I am on a product PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.And("I choose to add the product to  the bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.Then("The product is placed in users bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PDP templates check")]
        [NUnit.Framework.TestCaseAttribute("Fashion 1", null)]
        [NUnit.Framework.TestCaseAttribute("Fashion 2", null)]
        [NUnit.Framework.TestCaseAttribute("Buggies", null)]
        [NUnit.Framework.TestCaseAttribute("Pairs", null)]
        [NUnit.Framework.TestCaseAttribute("Bedding", null)]
        [NUnit.Framework.TestCaseAttribute("Towels", null)]
        [NUnit.Framework.TestCaseAttribute("Tableware", null)]
        [NUnit.Framework.TestCaseAttribute("Gift Card", null)]
        public virtual void PDPTemplatesCheck(string pDPTemplate, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PDP templates check", null, exampleTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 15
 testRunner.Given(string.Format("I want to check \'{0}\' is displaying correctly", pDPTemplate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.Then("When I navigate there I am served correct infomation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fashion Buying Controls and Section")]
        [NUnit.Framework.TestCaseAttribute("Brand", null)]
        [NUnit.Framework.TestCaseAttribute("Title", null)]
        [NUnit.Framework.TestCaseAttribute("Price", null)]
        [NUnit.Framework.TestCaseAttribute("ID", null)]
        [NUnit.Framework.TestCaseAttribute("Colour", null)]
        [NUnit.Framework.TestCaseAttribute("Size", null)]
        [NUnit.Framework.TestCaseAttribute("Quantity", null)]
        [NUnit.Framework.TestCaseAttribute("Delivery & Returns", null)]
        [NUnit.Framework.TestCaseAttribute("Add To Bag", null)]
        public virtual void FashionBuyingControlsAndSection(string buyingControls, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Fashion Buying Controls and Section", null, exampleTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 29
  testRunner.Given("I want to check \'Fashion 1\' is displaying correctly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
  testRunner.When("I validate Section on PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
  testRunner.Then(string.Format("the \'{0}\' section contains the following", buyingControls), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GiftCard Buying Controls Section")]
        [NUnit.Framework.TestCaseAttribute("Brand", null)]
        [NUnit.Framework.TestCaseAttribute("Title", null)]
        [NUnit.Framework.TestCaseAttribute("Price", null)]
        [NUnit.Framework.TestCaseAttribute("ID", null)]
        [NUnit.Framework.TestCaseAttribute("Quantity", null)]
        [NUnit.Framework.TestCaseAttribute("UK Only Delivery Message", null)]
        [NUnit.Framework.TestCaseAttribute("Delivery & Returns", null)]
        public virtual void GiftCardBuyingControlsSection(string buyingControls, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GiftCard Buying Controls Section", null, exampleTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 45
  testRunner.Given("I want to check \'Gift Card\' is displaying correctly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 46
  testRunner.Then(string.Format("the \'{0}\' section contains the following", buyingControls), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Accessories Buying Controls and Section")]
        [NUnit.Framework.TestCaseAttribute("Brand", null)]
        [NUnit.Framework.TestCaseAttribute("Title", null)]
        [NUnit.Framework.TestCaseAttribute("Price", null)]
        [NUnit.Framework.TestCaseAttribute("ID", null)]
        [NUnit.Framework.TestCaseAttribute("Colour", null)]
        [NUnit.Framework.TestCaseAttribute("Quantity", null)]
        [NUnit.Framework.TestCaseAttribute("Delivery & Returns", null)]
        [NUnit.Framework.TestCaseAttribute("Add To Bag", null)]
        public virtual void AccessoriesBuyingControlsAndSection(string buyingControls, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accessories Buying Controls and Section", null, exampleTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 58
  testRunner.Given("I want to check \'Fashion 2\' is displaying correctly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 59
  testRunner.When("I validate Section on PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
  testRunner.Then(string.Format("the \'{0}\' section contains the following", buyingControls), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Buggies Buying Controls and Section")]
        [NUnit.Framework.TestCaseAttribute("Brand", null)]
        [NUnit.Framework.TestCaseAttribute("Title", null)]
        [NUnit.Framework.TestCaseAttribute("Price", null)]
        [NUnit.Framework.TestCaseAttribute("ID", null)]
        [NUnit.Framework.TestCaseAttribute("Colour", null)]
        [NUnit.Framework.TestCaseAttribute("Quantity", null)]
        [NUnit.Framework.TestCaseAttribute("Delivery & Returns", null)]
        [NUnit.Framework.TestCaseAttribute("Add To Bag", null)]
        public virtual void BuggiesBuyingControlsAndSection(string buyingControls, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buggies Buying Controls and Section", null, exampleTags);
#line 72
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 73
  testRunner.Given("I want to check \'Buggies\' is displaying correctly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 74
  testRunner.When("I validate Section on PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
  testRunner.Then(string.Format("the \'{0}\' section contains the following", buyingControls), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pairs Buying Controls and Section")]
        [NUnit.Framework.TestCaseAttribute("Brand", null)]
        [NUnit.Framework.TestCaseAttribute("Title", null)]
        [NUnit.Framework.TestCaseAttribute("Price", null)]
        [NUnit.Framework.TestCaseAttribute("ID", null)]
        [NUnit.Framework.TestCaseAttribute("Colour", null)]
        [NUnit.Framework.TestCaseAttribute("Size", null)]
        [NUnit.Framework.TestCaseAttribute("Quantity", null)]
        [NUnit.Framework.TestCaseAttribute("Delivery & Returns", null)]
        [NUnit.Framework.TestCaseAttribute("Add To Bag", null)]
        public virtual void PairsBuyingControlsAndSection(string buyingControls, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pairs Buying Controls and Section", null, exampleTags);
#line 87
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 88
  testRunner.Given("I want to check \'Pairs\' is displaying correctly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 89
  testRunner.When("I validate Section on PDP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
  testRunner.Then(string.Format("the \'{0}\' section contains the following", buyingControls), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
